### ISSUE TITLE
Doesn't respond to multiple messages in a single transaction (repeated start)

### ISSUE THREAD

**Issue by nigelorr** [dgatf/I2C-slave-multi-address-RP2040#2]
Messages targeted for an INA260 using the [Adafruit INA260 library](https://reference.arduino.cc/reference/en/libraries/adafruit-ina260-library/) fail to get a response if they use repeated start, for example the PulseView capture below shows a successful read, then a failed read at a specific address which uses I2C repeat start.

![0x40_Repeat_Start_Fails](https://github.com/dgatf/I2C-slave-multi-address-RP2040/assets/812323/8ed73d82-643a-4ccd-9f1c-49090c4070d2)

**Comment by nigelorr** [comment]
It happens because there is no stop bit, so the stop_handler function is never triggered. In I2C terms, the library only supports a single "message" in a "transaction".

I have a fix which shuffles the instructions around and adds a trigger of IRQ 1 in start_condition. It's a bit of a bodge, as I'm not sure if it will break some other use cases, but will share it tomorrow.

**Comment by dgatf** [comment]
Fixed with #5
